Increase clarity of CUDA errors by including excerpt from logs
CUDA 12.9 introduced the CUDA_LOG_FILE=... env var which prints very detailed and useful explanation of CUDA errors (e.g., the opaque and cryptic "invalid value" resolves to exactly what argument had a bad value and why).

A suggestion to users to enable this was included in https://github.com/pytorch/pytorch/pull/181011.

This same error log is also accessible programatically, thus a more robust approach is to systematically include the relevant lines from the log when we encounter a CUDA error and raise an exception. The API allows to do this very cleanly as we can get a pointer to the end of the log before issuing a call, and thus narrow down the messages that were logged during that call, and avoid spurious ones. (We might still get some noise during multi-threaded execution though...).

This comes at the extra cost of one extra CUDA driver call before every CUDA call, but it looks like a very lightweight operation.

There is extra complexity in this approach coming from the fact that these are driver-level functions, thus we need a careful indirection to access them, which makes the code a bit cumbersome.

Here's an example of what this gives:

```
AcceleratorError: CUDA error: invalid argument
Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
The CUDA driver logged these messages, which may provide useful details:
[05:12:55.030][281460752730784][CUDA][E] Device-launched graphs and conditional nodes do not support MEM_ALLOC nodes
[05:12:55.031][281460752730784][CUDA][E] Returning 1 (CUDA_ERROR_INVALID_VALUE) from cuGraphInstantiateWithFlags
```

ghstack-source-id: ac8d2b0bb316a84982b449faf11d3ddd4ebc5016
ghstack-comment-id: 5104215809
Pull-Request: https://github.com/pytorch/pytorch/pull/191334